<?php

namespace TaskPlannerBundle\Repository;

use Doctrine\ORM\EntityRepository;
use TaskPlannerBundle\Entity\Task;


/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function findUserOldTask($user){
        return $this->getEntityManager()->createQuery(
            'SELECT t FROM TaskPlannerBundle:Task t WHERE t.deadline <= :date AND t.user = :user ORDER BY t.deadline'
        )
            ->setParameter('date', new \DateTime())
            ->setParameter('user', $user )
            ->getResult();
    }


    public function findUserCurrentTask($user){
        return $this->getEntityManager()->createQuery(
            'SELECT t FROM TaskPlannerBundle:Task t WHERE t.deadline > :date AND t.user = :user ORDER BY t.deadline'
        )
            ->setParameter('date', new \DateTime())
            ->setParameter('user', $user )
            ->getResult();
    }
}
